export enum LogAction {
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',
  PRODUCT_RESTORED = 'PRODUCT_RESTORED',

  VARIANT_CREATED = 'VARIANT_CREATED',

  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED = 'WAREHOUSE_UPDATED',
  WAREHOUSE_DELETED = 'WAREHOUSE_DELETED',
  WAREHOUSE_ACTIVATED = 'WAREHOUSE_ACTIVATED',
  WAREHOUSE_DEACTIVATED = 'WAREHOUSE_DEACTIVATED',

  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED = 'SUPPLIER_DELETED',

  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED = 'CUSTOMER_DELETED',

  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',

  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  STOCK_ADJUSTED = 'STOCK_ADJUSTED',

  SHIPMENT_SHIPPED = 'SHIPMENT_SHIPPED',
  SHIPMENT_CANCELLED = 'SHIPMENT_CANCELLED',
}
