export enum LogEntityType {
  PRODUCT = 'PRODUCT',
  VARIANT = 'VARIANT',
  WAREHOUSE = 'WAREHOUSE',
  TRANSACTION = 'TRANSACTION',
  USER = 'USER',
  SUPPLIER = 'SUPPLIER',
  CUSTOMER = 'CUSTOMER',
}
