export enum LogAction {
  // Product
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',
  PRODUCT_UNARCHIVED = 'PRODUCT_UNARCHIVED',

  // Warehouse
  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED = 'WAREHOUSE_UPDATED',
  WAREHOUSE_DELETED = 'WAREHOUSE_DELETED',
  WAREHOUSE_ACTIVATED = 'WAREHOUSE_ACTIVATED',
  WAREHOUSE_DEACTIVATED = 'WAREHOUSE_DEACTIVATED',

  // Supplier
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED = 'SUPPLIER_DELETED',

  // Customer
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED = 'CUSTOMER_DELETED',

  // User / Admin
  MANAGER_INVITED = 'MANAGER_INVITED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',

  // Transactions / Stock
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_CANCELLED = 'TRANSACTION_CANCELLED',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  STOCK_ADJUSTED = 'STOCK_ADJUSTED',
}
